### PR TITLE
Fix testing

### PR DESCRIPTION
**Pull request by ndaelman-hu**
Minor changes to enable testing (when run in the dev setup from the NOMAD project folder `dependencies/schema/simulation/data`).

### CODE REVIEW

**Comment by JosePizarro3** [comment]
What is the issue here? I think the relative imports, especially in `__init__.py` were correct. See simulation/run e.g.

@ladinesa, any idea of this?

**Comment by ndaelman-hu** [comment]
> What is the issue here? I think the relative imports, especially in `__init__.py` were correct. See simulation/run e.g.
> 
> @ladinesa, any idea of this?

They weren't working for me. Even after fixing this, there's still a problem with `matid.classifications`. Am looking into it now.

Getting relative imports to work is a bit tricky, especially with nested projects. If you cross-reference with **other dependencies,** you'll see that **they also follow this kind of import statement**, i.e. relative to their own project root. That is like an absolute path from their perspective and thus robuster.

**Comment by ladinesa** [comment]
> What is the issue here? I think the relative imports, especially in `__init__.py` were correct. See simulation/run e.g.
> 
> @ladinesa, any idea of this?

sorry I cannot follow the problem. In your simulationdata/init.py you have  ```from .system import ModelSystem```, so in principle your can do ```from simulationdata import ModelSystem```, ```from simulationdata.system import Model``` won't work unles you have ```from . import system```

**Comment by ndaelman-hu** [comment]
@JosePizarro3 Fixed the matid import, but hit another dead end. I either use your branch 1728, but it hasn't been rebased to today's changes yet.

Moreover, I also suggest that for the time being we keep the classes that you introduce there in this plugin (for now, while we're generating a structure), unless it really breaks something.

**Comment by JosePizarro3** [comment]
These relative imports should and do work. The imports in MatID that you implemented are anyways wrong.

In any case, please, wait for #1 to be merged. Now you are working on top of develop.

I will push the changes to gitlab next week.

**Comment by ndaelman-hu** [comment]
Adding `__init__.py` to `tests` and re-building has solved the issue, while maintaining the relative paths.
Kudos goes to @ladinesa . He also pointed out that for dynamically installed Python envs, absolute paths are fine (better even), but not when dealing regular pip installs.

@JosePizarro3 I rebased to `1-initial-polishing-of-modelsystem`. The effective change is just adding an empty file, so you can also apply this directly to your branch before merging.

**Comment by JosePizarro3** [comment]
> Adding `__init__.py` to `tests` and re-building has solved the issue, while maintaining the relative paths. Kudos goes to @ladinesa . He also pointed out that for dynamically installed Python envs, absolute paths are fine (better even), but not when dealing regular pip installs.
> 
> @JosePizarro3 I rebased to `1-initial-polishing-of-modelsystem`. The effective change is just adding an empty file, so you can also apply this directly to your branch before merging.

Can you target the branch 1-initial-polishing? :)

**Pull request merged**
