### PR TITLE
added zenodo doi

### PR DESCRIPTION
**Pull request by JFRudzinski**
@JosePizarro3 FYI

### CODE REVIEW

**Comment by JosePizarro3** [comment]
And in the How to cite part of the readme :-)

**Comment by JFRudzinski** [comment]
Can you approve/review @JosePizarro3 ?

**Review by JosePizarro3 — APPROVED** [review]
Cannot you bypass the protection?

**Comment by JFRudzinski** [comment]
> Cannot you bypass the protection?

Yes of course, I just wasn't sure how important it was to you. I will do so in the future in cases that it is obviously ok, sorry :flushed:

**Pull request merged**
