### PR TITLE
115 issues with dft xc extraction

### PR DESCRIPTION
**Pull request by ndaelman-hu**
Fix reported issues of the libxc name normalization

### CODE REVIEW

**Review by JosePizarro3 — APPROVED** [review]

**Comment by ndaelman-hu** [comment]
Thank you for reviewing and approving. In the future, pls leave the merging to the assignee, though. When this got merged, it has my name on it, i.e. it's as if I sign off on it. As with official documents, one doesn't forge signatures, either. Similarly, for deleting active branches.

In this case, there's little harm (and I don't have to revert `develop`), as the fix to 1 was already completed and stands separately from issue 2. I was just waiting for a reply before fixing 2 and merging both together.
If the user needs one fix sooner, they / you can let me know, and we see to split the patches. Now, I actually don't know how urgent their issue 2 is.

**Comment by JosePizarro3** [comment]
Next time, please, be more verbose on what you have to do or not. But at least there is no harm, so no worries; just open a new pr if needed.

**Comment by ndaelman-hu** [comment]
> Next time, please, be more verbose on what you have to do or not. But at least there is no harm, so no worries; just open a new pr if needed.

I'm always open to providing more information. Feel free to ask if something isn't clear.

**Comment by JosePizarro3** [comment]
Just add a todo with some list so we know if something is missing

**Pull request merged**
